apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "driver.controller.name" . }}
  namespace: {{ include "driver.namespace.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ include "driver.controller.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ include "driver.controller.name" . }}
        {{- if (include "driver.labels" .) }}
        {{- include "driver.labels" . | indent 8}}
        {{- end }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: {{ include "driver.serviceaccount.name" .}}
      containers:
        - name: csi-s3
          image: {{ include "driver.image" .}}
          args:
            - "--endpoint=unix://$(CSI_ADDRESS)"
            - "--nodeid=$(NODE_ID)"
            - {{ include "log.level" .}}
          env:
            - name: CSI_ADDRESS
              value: /run/csi/socket
            - name: NODE_ID
              value: controller
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGMAP_NAME
              value: {{ include "driver.configmap.name" . }}
            - name: SECRET_NAME
              value: {{ include "driver.secret.name" . }}
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          args:
            - "--leader-election"
            - "--leader-election-namespace=$(NAMESPACE)"
            - {{ include "log.level" .}}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: socket-dir
          emptyDir: {}