apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "driver.node.name" . }}
  namespace: {{ include "driver.namespace.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ include "driver.node.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ include "driver.node.name" . }}
        {{- if (include "driver.labels" .) }}
        {{- include "driver.labels" . | indent 8}}
        {{- end }}
    spec:
      serviceAccountName: {{ include "driver.serviceaccount.name" .}}
      containers:
        - name: csi-s3
          image: {{ include "driver.image" .}}
          args:
            - "--endpoint=unix://$(CSI_ADDRESS)"
            - "--nodeid=$(NODE_ID)"
            - {{ include "log.level" .}}
          env:
            - name: CSI_ADDRESS
              value: /run/csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGMAP_NAME
              value: {{ include "driver.configmap.name" . }}
            - name: SECRET_NAME
              value: {{ include "driver.secret.name" . }}
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi/
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: fuse
              mountPath: /dev/fuse
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
          args:
            - "--csi-address=$(CSI_ADDRESS)"
            - "--kubelet-registration-path=$(REGISTRATION_PATH)"
            - {{ include "log.level" .}}
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
            - name: REGISTRATION_PATH
              value: /var/lib/kubelet/plugins/{{ include "driver.name" . | replace "-" "."}}/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: socket-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ include "driver.name" . | replace "-" "."}}/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: fuse
          hostPath:
            path: /dev/fuse
        
