apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-s3-controller
  namespace: csi-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-s3-controller
  template:
    metadata:
      labels:
        app: csi-s3-controller
        app.kubernetes.io/part-of: minio-csi-s3
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccountName: csi-s3
      containers:
        - name: csi-s3
          image: cshoch3/k8s-csi-s3-minio:dev
          args:
            - "--endpoint=unix://$(CSI_ADDRESS)"
            - "--nodeid=$(NODE_ID)"
            - "--mountBinary=/usr/local/bin/mount-s3"
            - "--v=4"
          env:
            - name: CSI_ADDRESS
              value: /run/csi/socket
            - name: NODE_ID
              value: controller
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGMAP_NAME
              value: csi-s3-config
            - name: SECRET_NAME
              value: csi-s3-secret
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          args:
            - "--leader-election"
            - "--leader-election-namespace=$(NAMESPACE)"
            - "--v=4"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: socket-dir
          emptyDir: {}