apiVersion: v1
name: minio-csi-s3
version: 1.0.2
appVersion: 1.0.1
description: An open source k8s-csi-s3 driver for S3 compatible object storage, tested with MinIO / AIStore Object Storage.
keywords:
- kuberetes
- csi
- s3
- minio
sources:
- https://github.com/smou/k8s-csi-s3
maintainers:
- email: smou@gmail.com
  name: Christopher Sch√ºtze