apiVersion: v1
name: minio-csi-s3
version: 1.0.3
appVersion: 1.1.0
description: An open source kubernetes minio-csi-s3 driver for S3 compatible object storage, tested with MinIO / AIStore Object Storage.
keywords:
- kuberetes
- csi
- s3
- minio
sources:
- https://github.com/smou/minio-csi-s3
maintainers:
- email: smou@gmail.com
  name: Christopher Sch√ºtze